import { useMemo, useState } from "react";

type Case = { id: string; merchant: string; type: string; amount: string; route: string; score: string; coverage: string; age: string; status: string; reason: string };
const seedCases: Case[] = [
  { id: "OL-0241", merchant: "Abarrotes La Esperanza", type: "Abarrotes · Iztapalapa", amount: "MXN 20,000", route: "COMMITTEE", score: "68.4", coverage: "60%", age: "12 min", status: "Needs review", reason: "Identity and bureau evidence are not verified." },
  { id: "OL-0239", merchant: "Tienda San Luis", type: "Abarrotes · Nezahualcóyotl", amount: "MXN 25,000", route: "AUTO-APPROVE", score: "84.1", coverage: "92%", age: "28 min", status: "Ready", reason: "Strong cash-flow capacity and consistent operating evidence." },
  { id: "OL-0235", merchant: "Taquería La Aurora", type: "Taquería · Coyoacán", amount: "MXN 32,000", route: "DECLINE", score: "41.2", coverage: "48%", age: "1 hr", status: "Blocked", reason: "Debt coverage is below the minimum and identity is incomplete." },
];

export default function AnalystConsole() {
  const [selectedId, setSelectedId] = useState(seedCases[0].id);
  const [filter, setFilter] = useState("all");
  const [decision, setDecision] = useState<string | null>(null);
  const selected = useMemo(() => seedCases.find((item) => item.id === selectedId) ?? seedCases[0], [selectedId]);
  const visible = filter === "all" ? seedCases : seedCases.filter((item) => item.route.toLowerCase().includes(filter));
  return <div className="analyst-console">
    <header className="analyst-console__header"><div><span className="pilot-workspace__eyebrow">Olin analyst console</span><h2>Review queue</h2></div><div className="analyst-console__header-meta"><span>COHORT shadow_2026_07</span><strong>3 open cases</strong></div></header>
    <div className="analyst-console__body">
      <aside className="analyst-console__queue"><div className="queue-head"><strong>Applications</strong><select value={filter} onChange={(event) => setFilter(event.target.value)} aria-label="Filter applications"><option value="all">All routes</option><option value="committee">Committee</option><option value="auto-approve">Auto-approve</option><option value="decline">Decline</option></select></div>{visible.map((item) => <button key={item.id} type="button" className={`queue-item ${selected.id === item.id ? "is-selected" : ""}`} onClick={() => { setSelectedId(item.id); setDecision(null); }}><span><strong>{item.merchant}</strong><small>{item.id} · {item.type}</small></span><span className={`queue-route queue-route--${item.route.toLowerCase().replace("-", "")}`}>{item.route}</span><small>{item.age}</small></button>)}</aside>
      <main className="analyst-console__detail"><div className="case-detail__top"><div><span className="case-id">{selected.id} · SHADOW CASE</span><h3>{selected.merchant}</h3><p>{selected.type} · requested {selected.amount}</p></div><span className="case-status">{decision ?? selected.status}</span></div><div className="case-metrics"><div><span>Olin score</span><strong>{selected.score}</strong><small>confidence interval · synthetic</small></div><div><span>Coverage</span><strong>{selected.coverage}</strong><small>signals available</small></div><div><span>Route</span><strong>{selected.route}</strong><small>human review required</small></div></div><section className="signal-table"><div className="signal-table__head"><strong>Evidence ledger</strong><span>source status</span></div>{[["Círculo de Crédito", selected.route === "DECLINE" ? "Missing" : "Consent required"],["Bank cash flow / Syncfy", "Mock sandbox"],["FMCG purchases", "Mock evidence"],["Identity / INE", selected.route === "AUTO-APPROVE" ? "Verified" : "Missing"]].map(([label, value]) => <div className="signal-row" key={label}><strong>{label}</strong><span className={value === "Missing" ? "is-missing" : value.includes("Mock") ? "is-mock" : "is-pending"}>{value}</span></div>)}</section><div className="case-reason"><strong>Decision rationale</strong><p>{selected.reason}</p></div><section className="analyst-actions"><div><span>Partner decision</span><small>For shadow comparison only. No disbursement.</small></div><div className="action-buttons"><button type="button" onClick={() => setDecision("Partner approved")}>Approve</button><button type="button" onClick={() => setDecision("Partner declined")}>Decline</button><button type="button" onClick={() => setDecision("More evidence requested")}>Request evidence</button></div></section><div className="case-timeline"><strong>Audit timeline</strong><ol><li><span>09:42</span>Case created with merchant consent</li><li><span>09:43</span>Signals evaluated and coverage calculated</li><li><span>Now</span>{decision ?? "Awaiting analyst / partner action"}</li></ol></div></main>
    </div>
  </div>;
}
